version: "3.7"

volumes:
  sock:
    name: sock

configs:
  nginx_config_6x:
    file: ./nginx.conf
  php_fpm_config_6x:
    file: ./php-fpm.conf
  php_sources_6x:
    file: ./source.php

services:
  nginx:
    image: registry.skyeng.tv/infra/test-nginx
    ports:
      - published: 80
        target: 80
    configs:
      - source: nginx_config_6x
        target: /etc/nginx/conf.d/default.conf
    healthcheck:
      test: ["CMD", "curl", "127.0.0.1"]
      interval: 5s
      timeout: 5s
      start_period: 10s
    deploy:
      mode: replicated
      replicas: 1
#      placement:
#        constraints:
#          - node.hostname == s35-crm
      update_config:
        parallelism: 0
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 0
        failure_action: pause
        order: start-first

  php-fpm:
    image: php:7.3-fpm-alpine
    configs:
      - source: php_fpm_config_6x
        target: /usr/local/etc/php-fpm.d/zz-docker.conf
      - source: php_sources_6x
        target: /opt/app/index.php
    environment:
      PHP_VERSION: 6x
    healthcheck:
      test: php -r 'if (!@fsockopen("localhost:9000")) die(1);'
      interval: 5s
      timeout: 5s
      start_period: 10s
    entrypoint: sh -c "echo warmup_some_cache && sleep 5 && echo finish! && exec docker-php-entrypoint php-fpm"
    deploy:
      mode: replicated
      replicas: 1
#      placement:
#        constraints:
#          - node.hostname == s35-crm
      update_config:
        parallelism: 0
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 0
        failure_action: pause
        order: start-first
